import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import axios from 'axios';
import { FiDownload, FiMessageSquare } from 'react-icons/fi';

const AIItineraryGeneratorPage = () => {
  const navigate = useNavigate();
  const [formData, setFormData] = useState({
    destination: '',
    startDate: '',
    endDate: '',
    requirements: '',
  });
  const [loading, setLoading] = useState(false);
  const [itinerary, setItinerary] = useState('');
  const [error, setError] = useState('');
  // Removed unused itineraryRef

  const handleChange = (e) => {
    const { name, value } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: value
    }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError('');
    
    try {
      const response = await axios.post('/api/v1/ai-itinerary/generate', {
        destination: formData.destination,
        startDate: formData.startDate,
        endDate: formData.endDate,
        requirements: formData.requirements,
      });
      
      setItinerary(response.data.itinerary);
    } catch (err) {
      console.error('Error generating itinerary:', err);
      setError('Failed to generate itinerary. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  const downloadItinerary = () => {
    // Create a new window with the itinerary content
    const printWindow = window.open('', '', 'width=800,height=600');
    const title = `Travel Itinerary - ${formData.destination} (${formData.startDate} to ${formData.endDate})`;
    
    // Get the HTML content of the itinerary
    const content = document.getElementById('itinerary-content').innerHTML;
    
    // Create a clean HTML document for printing with watermark
    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>${title}</title>
        <style>
          @page {
            @top-right {
              content: "Bookmysight.com";
              font-size: 10px;
              color: #999;
              font-style: italic;
            }
          }
          body { 
            font-family: Arial, sans-serif; 
            line-height: 1.6; 
            padding: 20px;
            position: relative;
          }
          .watermark {
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%) rotate(-45deg);
            transform-origin: center center;
            font-size: 48px;
            font-weight: bold;
            color: rgba(0, 0, 0, 0.08);
            pointer-events: none;
            white-space: nowrap;
            z-index: 9999;
          }
          h1 { 
            color: #1a365d; 
            margin-bottom: 10px; 
            position: relative;
            z-index: 1;
          }
          h2 { 
            color: #2c5282; 
            margin-top: 20px; 
            margin-bottom: 10px; 
            position: relative;
            z-index: 1;
          }
          h3 { 
            color: #2b6cb0; 
            margin-top: 15px; 
            margin-bottom: 5px; 
            position: relative;
            z-index: 1;
          }
          p { 
            margin: 10px 0; 
            position: relative;
            z-index: 1;
          }
          ul { 
            margin: 10px 0; 
            padding-left: 20px; 
            position: relative;
            z-index: 1;
          }
          li { 
            margin: 5px 0; 
            position: relative;
            z-index: 1;
          }
          .header { 
            text-align: center; 
            margin-bottom: 20px; 
            position: relative;
            z-index: 1;
          }
          .section { 
            margin-bottom: 30px; 
            position: relative;
            z-index: 1;
          }
          .footer { 
            margin-top: 40px; 
            font-size: 0.9em; 
            color: #666; 
            text-align: center; 
            position: relative;
            z-index: 1;
          }
          @media print {
            .watermark {
              display: block !important;
            }
          }
        </style>
      </head>
      <body>
        <div class="watermark">Bookmysight.com</div>
        <div class="header">
          <h1>${title}</h1>
          <p>Generated on ${new Date().toLocaleDateString()}</p>
        </div>
        <div class="itinerary">
          ${content}
        </div>
        <div class="footer">
          <p>Generated by <a href="https://bookmysight.com" target="_blank">Bookmysight.com</a></p>
        </div>
      </body>
      </html>
    `;
    
    // Write the content and trigger print
    printWindow.document.write(html);
    printWindow.document.close();
    
    // Wait for content to load before printing
    printWindow.onload = function() {
      printWindow.print();
      // printWindow.close(); // Uncomment to close after printing
    };
  };
  
  const shareOnWhatsApp = () => {
    // Create a text version of the itinerary
    let text = `*${formData.destination} Travel Itinerary*\n\n`;
    
    // Add dates
    text += `*Dates:* ${formData.startDate} to ${formData.endDate}\n\n`;
    
    // Add itinerary days
    const days = parseItinerary(itinerary);
    days.forEach(day => {
      text += `*${day.day}: ${day.title}*\n`;
      // Convert HTML to plain text for WhatsApp
      const plainText = day.content
        .replace(/<[^>]*>?/gm, '') // Remove HTML tags
        .replace(/&nbsp;/g, ' ')   // Replace HTML spaces
        .replace(/\s+/g, ' ')      // Collapse multiple spaces
        .trim();
      
      text += `${plainText}\n\n`;
    });
    
    // Encode the text for URL
    const encodedText = encodeURIComponent(text);
    
    // Open WhatsApp with the text
    window.open(`https://wa.me/?text=${encodedText}`, '_blank');
  };

  const parseItinerary = (itineraryText) => {
    if (!itineraryText) return [];
    
    // First, try to split by day sections
    let daySections = [];
    
    // Try different patterns to split days
    const dayPatterns = [
      /(###?\s*Day\s+\d+[\s\-:].*?(?=\n###?\s*Day\s+\d+[\s\-:]|$))/gis,  // Markdown style with Day X: or Day X -
      /(Day\s+\d+[\s\-:].*?(?=\nDay\s+\d+[\s\-:]|$))/gis,           // Plain text with Day X:
      /(###?\s*\d+[\s\-:].*?(?=\n###?\s*\d+[\s\-:]|$))/gis,          // Just numbers with : or -
    ];
    
    // Try each pattern until we find a good split
    for (const pattern of dayPatterns) {
      const matches = [...itineraryText.matchAll(pattern)];
      if (matches.length > 1) {
        daySections = matches.map(match => match[0].trim());
        break;
      }
    }
    
    // If no day sections found, try to split by date patterns
    if (daySections.length <= 1) {
      const datePattern = /(\w+,\s+\d{4}-\d{2}-\d{2}.*?(?=\n\w+,\s+\d{4}-\d{2}-\d{2}|$))/gis;
      const dateMatches = [...itineraryText.matchAll(datePattern)];
      if (dateMatches.length > 1) {
        daySections = dateMatches.map(match => match[0].trim());
      }
    }
    
    // If still no sections found, try to split by double newlines
    if (daySections.length <= 1) {
      daySections = itineraryText.split(/\n\s*\n+/).filter(section => 
        section.trim().length > 0 && 
        !section.trim().startsWith('---') &&
        !section.trim().startsWith('# Important Travel Tips')
      );
    }
    
    // If no sections at all, return the whole text as one section
    if (daySections.length === 0) {
      return [{
        day: 'Itinerary',
        title: 'Your Travel Plan',
        content: `<div class="prose max-w-none">${itineraryText
          .replace(/\n\s*\n/g, '</p><p>')
          .replace(/\n/g, ' ')}
          </div>`
      }];
    }
    
    return daySections.map((section, index) => {
      // Extract day number and title
      let dayNumber = index + 1;
      let title = `Day ${dayNumber}`;
      
      // Try to extract day number and title from section
      const dayMatch = section.match(/###?\s*(?:Day\s*)?(\d+)[\s\-:](.*?)(?=\n|###|$)/i) || 
                     section.match(/(?:Day\s*)?(\d+)[\s\-:](.*?)(?=\n|###|$)/i);
      
      if (dayMatch) {
        dayNumber = dayMatch[1] || dayNumber;
        title = (dayMatch[2] || `Day ${dayNumber}`).trim();
      } 
      // Try to extract date from section
      else {
        const dateMatch = section.match(/(\w+,\s+\d{4}-\d{2}-\d{2})(?:\s*-\s*(.*?))?(?=\n|$)/i);
        if (dateMatch) {
          title = dateMatch[2] ? `${dateMatch[1].trim()} - ${dateMatch[2].trim()}` : dateMatch[1].trim();
        }
      }
      
      // Clean up the content
      let content = section
        // Remove day/date headers
        .replace(/^###?\s*(?:Day\s*)?\d+[\s\-:].*?\n/i, '')
        .replace(/^\w+,\s+\d{4}-\d{2}-\d{2}(?:\s*-\s*.*?)?\n?/i, '')
        .trim();
      
      // Format the content with proper HTML structure
      const formattedContent = content
        // Handle time-based sections (e.g., "Morning (08:00 - 10:00):")
        .replace(/^(\w+)\s*\(?(\d{1,2}:\d{2}\s*-\s*\d{1,2}:\d{2})\)?\s*:?/gim, 
          (match, timeOfDay, timeRange) => {
            return `</p><h3 class="text-md font-semibold mt-4 mb-2 text-blue-700">${timeOfDay}${timeRange ? ` (${timeRange})` : ''}</h3><p>`;
          })
        // Handle bold text
        .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
        // Handle italic text
        .replace(/\*(.*?)\*/g, '<em>$1</em>')
        // Handle lists with bullet points
        .replace(/^\s*[-*•]\s+(.+)$/gm, '<li>$1</li>')
        // Handle numbered lists
        .replace(/^\s*\d+\.\s+(.+)$/gm, '<li>$1</li>')
        // Handle travel tips
        .replace(/Travel Tip:/g, '<strong class="text-blue-600">Travel Tip:</strong>')
        // Split into paragraphs
        .split(/\n\s*\n+/)
        .filter(para => {
          // Skip empty paragraphs and section dividers
          const trimmed = para.trim();
          return trimmed.length > 0 && 
                 !trimmed.startsWith('---') && 
                 !trimmed.startsWith('###') &&
                 !trimmed.match(/^Day\s+\d+/i) &&
                 !trimmed.match(/^\w+,\s+\d{4}-\d{2}-\d{2}/i);
        })
        .map(para => {
          // If paragraph contains list items, wrap in ul
          if (para.includes('<li>')) {
            return `<ul class="space-y-2 mb-4 pl-5 list-disc">${para}</ul>`;
          }
          // If it's a heading
          if (para.match(/^#+\s/)) {
            const level = para.match(/^#+/)[0].length;
            const text = para.replace(/^#+\s*/, '');
            return `<h${Math.min(level + 1, 6)} class="text-lg font-semibold mt-6 mb-3">${text}</h${Math.min(level + 1, 6)}>`;
          }
          // Regular paragraph
          return `<p class="mb-4">${para}</p>`;
        })
        .join('');
      
      return {
        day: `Day ${dayNumber}`,
        title: title,
        content: formattedContent
      };
    });
  };

  const itineraryDays = parseItinerary(itinerary);

  return (
    <div className="min-h-screen bg-gray-50 py-8 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        <div className="mb-6">
          <button
            onClick={() => navigate('/')}
            className="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-gray-600 hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500"
          >
            <svg className="mr-2 h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
            </svg>
            Back to Home
          </button>
        </div>
        <div className="text-center mb-10">
          <h1 className="text-3xl font-extrabold text-gray-900 sm:text-4xl mb-3">
            AI Itinerary Generator
          </h1>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            Create your perfect travel plan with AI
          </p>
        </div>

        <div className="bg-white shadow-xl rounded-2xl overflow-hidden mb-10 transition-all duration-300 hover:shadow-2xl">
          <div className="p-6 sm:p-8">
            <h2 className="text-xl font-semibold text-gray-800 mb-6">Plan Your Perfect Trip</h2>
            <form onSubmit={handleSubmit} className="space-y-6">
              <div className="grid grid-cols-1 gap-6 sm:grid-cols-2">
                <div className="space-y-1">
                  <label htmlFor="destination" className="block text-sm font-medium text-gray-700">
                    Destination
                  </label>
                  <div className="relative">
                    <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                      <svg className="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" />
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" />
                      </svg>
                    </div>
                    <input
                      type="text"
                      name="destination"
                      id="destination"
                      value={formData.destination}
                      onChange={handleChange}
                      className="pl-10 block w-full border border-gray-300 rounded-lg shadow-sm py-3 px-4 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      placeholder="e.g., Tokyo, Japan"
                      required
                    />
                  </div>
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div className="space-y-1">
                    <label htmlFor="startDate" className="block text-sm font-medium text-gray-700">
                      Start Date
                    </label>
                    <div className="relative">
                      <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                        <svg className="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                        </svg>
                      </div>
                      <input
                        type="date"
                        name="startDate"
                        id="startDate"
                        value={formData.startDate}
                        onChange={handleChange}
                        min={new Date().toISOString().split('T')[0]}
                        className="pl-10 block w-full border border-gray-300 rounded-lg shadow-sm py-3 px-4 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                        required
                      />
                    </div>
                  </div>

                  <div className="space-y-1">
                    <label htmlFor="endDate" className="block text-sm font-medium text-gray-700">
                      End Date
                    </label>
                    <div className="relative">
                      <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                        <svg className="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
                        </svg>
                      </div>
                      <input
                        type="date"
                        name="endDate"
                        id="endDate"
                        value={formData.endDate}
                        onChange={handleChange}
                        min={formData.startDate || new Date().toISOString().split('T')[0]}
                        className="pl-10 block w-full border border-gray-300 rounded-lg shadow-sm py-3 px-4 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                        required
                      />
                    </div>
                  </div>
                </div>

                <div className="space-y-1">
                  <label htmlFor="requirements" className="block text-sm font-medium text-gray-700">
                    Your Requirements
                  </label>
                  <div className="relative">
                    <div className="absolute top-3 left-3">
                      <svg className="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                      </svg>
                    </div>
                    <textarea
                      id="requirements"
                      name="requirements"
                      rows={3}
                      value={formData.requirements}
                      onChange={handleChange}
                      className="pl-10 block w-full border border-gray-300 rounded-lg shadow-sm py-3 px-4 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                      placeholder="E.g., Must-visit places, dietary restrictions, accessibility needs, etc."
                      required
                    />
                  </div>
                </div>
              </div>

              <div className="pt-2">
                <button
                  type="submit"
                  disabled={loading}
                  className={`w-full flex justify-center items-center py-3 px-6 border border-transparent rounded-lg shadow-sm text-base font-medium text-white bg-gradient-to-r from-blue-600 to-blue-700 hover:from-blue-700 hover:to-blue-800 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 transform transition-all duration-200 ${loading ? 'opacity-70 cursor-not-allowed' : 'hover:scale-[1.02]'}`}
                >
                  {loading ? (
                    <>
                      <svg className="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                      </svg>
                      Generating...
                    </>
                  ) : (
                    <>
                      <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19.428 15.428a2 2 0 00-1.022-.547l-2.387-.477a6 6 0 00-3.86.517l-.318.158a6 6 0 01-3.86.517L6.05 15.21a2 2 0 00-1.806.547M8 4h8l-1 1v5.172a2 2 0 00.586 1.414l5 5c1.26 1.26.367 3.414-1.415 3.414H4.828c-1.782 0-2.674-2.154-1.414-3.414l5-5A2 2 0 009 10.172V5L8 4z" />
                      </svg>
                      Generate Itinerary
                    </>
                  )}
                </button>
              </div>
            </form>

            {error && (
              <div className="mt-4 p-4 bg-red-50 border-l-4 border-red-400 rounded-r-lg">
                <div className="flex">
                  <div className="flex-shrink-0">
                    <svg className="h-5 w-5 text-red-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
                      <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clipRule="evenodd" />
                    </svg>
                  </div>
                  <div className="ml-3">
                    <p className="text-sm text-red-700">{error}</p>
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>

        {itinerary && (
          <div className="space-y-8">
            <div className="text-center">
              <h2 className="text-3xl font-bold text-gray-900">Your Custom Travel Itinerary</h2>
              <p className="mt-2 text-lg text-gray-600">
                {formData.destination} • {new Date(formData.startDate).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })} - {new Date(formData.endDate).toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
              </p>
              
              <div className="mt-6 flex justify-center space-x-4">
                <button
                  onClick={downloadItinerary}
                  className="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-green-600 hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-green-500"
                >
                  <FiDownload className="mr-2 h-4 w-4" />
                  Download PDF
                </button>
                <button
                  onClick={shareOnWhatsApp}
                  className="inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-[#25D366] hover:bg-[#128C7E] focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-[#25D366]"
                >
                  <FiMessageSquare className="mr-2 h-4 w-4" />
                  Share on WhatsApp
                </button>
              </div>
            </div>

            <div className="space-y-8" id="itinerary-content">
              {itineraryDays.length > 0 ? (
                itineraryDays.map((day, index) => (
                  <div key={index} className="bg-white rounded-xl shadow-lg overflow-hidden transition-all duration-300 hover:shadow-xl">
                    <div className="bg-gradient-to-r from-blue-600 to-blue-700 px-6 py-4">
                      <div className="flex items-center">
                        <div className="flex-shrink-0 bg-white bg-opacity-20 rounded-full p-2">
                          <span className="text-white font-bold text-lg">{day.day}</span>
                        </div>
                        <h3 className="ml-4 text-xl font-semibold text-white">{day.title}</h3>
                      </div>
                    </div>
                    <div className="p-6">
                      <div 
                        className="prose max-w-none"
                        dangerouslySetInnerHTML={{ __html: day.content }}
                      />
                    </div>
                  </div>
                ))
              ) : (
                <div 
                  className="prose max-w-none bg-white rounded-xl shadow-lg p-6"
                  dangerouslySetInnerHTML={{ __html: itinerary.replace(/\n/g, '<br />') }}
                />
              )}
            </div>

            <div className="bg-blue-50 rounded-xl p-6 text-center">
              <h3 className="text-lg font-medium text-blue-800">Need to make changes?</h3>
              <p className="mt-2 text-blue-700">Adjust your preferences above and generate a new itinerary.</p>
              <button
                onClick={() => window.scrollTo({ top: 0, behavior: 'smooth' })}
                className="mt-4 inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-blue-700 bg-blue-100 hover:bg-blue-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
              >
                <svg className="-ml-1 mr-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                </svg>
                Modify My Search
              </button>
              <button
                onClick={() => window.location.href = '/'}
                className="mt-4 inline-flex items-center px-4 py-2 border border-transparent text-sm font-medium rounded-md text-blue-700 bg-blue-100 hover:bg-blue-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
              >
                <svg className="-ml-1 mr-2 h-5 w-5" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6" />
                </svg>
                Home
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};

export default AIItineraryGeneratorPage;
