name: Deploy Backend to Azure Web App

on:
  push:
    branches: [dev]
    paths:
      - '**'
      - '!frontend/**'
  workflow_dispatch:

env:
  BUILD_NODE_VERSION: '22.x'  # For build process
  RUNTIME_NODE_VERSION: '22-lts'  # For Azure Web App runtime
  AZURE_WEBAPP_NAME: 'navi-backend'
  AZURE_RESOURCE_GROUP: 'nav_hosting'  # Resource group for Azure resources
  NODE_ENV: 'production'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.BUILD_NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
    
    - name: Install dependencies
      run: npm ci
      env:
        NODE_ENV: development
    
    - name: Build (if needed)
      run: npm run build --if-present
    
    - name: Set App Settings
      uses: azure/appservice-settings@v1
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
        app-settings-json: |
          [
            {
              "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
              "value": "true",
              "slotSetting": false
            }
          ]
    
    - name: Install production dependencies
      run: npm ci --only=production
      env:
        NODE_ENV: production
    
    - name: Create production .env
      run: |
        cat > .env << 'EOL'
        NODE_ENV=production
        # Azure App Service uses port 8080, which is correctly configured here.
        PORT=8080
        MONGODB_URI=${{ secrets.MONGODB_URI }}
        JWT_SECRET=${{ secrets.JWT_SECRET }}
        JWT_EXPIRE=30d
        JWT_COOKIE_EXPIRE=30
        EOL
    
    # Login to Azure with OIDC
    - name: Azure Login
      uses: azure/login@v1.6.0
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    # Create Azure resources
    - name: 'Create Azure Resources'
      uses: azure/CLI@v1
      with:
        inlineScript: |
          echo "Current active subscription:"
          az account show --output table
          
          if ! az appservice plan show --name navi-plan --resource-group nav_hosting --query "name" -o tsv; then
            echo "Creating App Service Plan..."
            az appservice plan create \
              --name navi-plan \
              --resource-group nav_hosting \
              --location eastasia \
              --sku B1 \
              --is-linux
          fi
          
          if ! az webapp show --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group nav_hosting --query "name" -o tsv; then
            echo "Creating Azure Web App..."
            az webapp create \
              --name ${{ env.AZURE_WEBAPP_NAME }} \
              --resource-group nav_hosting \
              --runtime "NODE|${{ env.RUNTIME_NODE_VERSION }}" \
              --plan "navi-plan"
          else
            echo "Web App already exists, skipping creation."
          fi

    - name: 'Configure Web App Settings'
      uses: azure/CLI@v1
      with:
        inlineScript: |
          echo "Configuring web app with production settings..."
          
          # Configure the web app with production settings
          az webapp config appsettings set --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --settings \
            NODE_ENV=production \
            WEBSITE_NODE_DEFAULT_VERSION=22-lts \
            WEBSITE_RUN_FROM_PACKAGE=1 \
            SCM_DO_BUILD_DURING_DEPLOYMENT=true \
            NPM_CONFIG_PRODUCTION=false
            
          # Configure Linux runtime and startup file
          az webapp config set \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --linux-fx-version "NODE|${{ env.RUNTIME_NODE_VERSION }}" \
            --startup-file "bash startup.sh"
          
          # Restart the app to apply changes
          az webapp restart --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ env.AZURE_RESOURCE_GROUP }}
          
    - name: 'Create ZIP package'
      run: |
        # Create a ZIP file of the current directory
        zip -r deployment.zip . -x '*.git*' '*.github*' '*.vscode*' 'node_modules/*' '.env*' '*.log'
    
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'Production'
        package: deployment.zip
    
    - name: Verify deployment
      run: |
        echo "Backend deployment to Azure Web App completed successfully!"
        echo "API URL: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
