name: Deploy Backend to Azure Web App

on:
  push:
    branches: [dev]
    paths:
      - '**'
      - '!frontend/**'
  workflow_dispatch:

env:
  BUILD_NODE_VERSION: '22.x'  # For build process
  RUNTIME_NODE_VERSION: '22-lts'  # For Azure Web App runtime
  AZURE_WEBAPP_NAME: 'navi-backend'
  AZURE_RESOURCE_GROUP: 'nav_hosting'  # Resource group for Azure resources

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.BUILD_NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
    
    - name: Install dependencies and build
      run: |
        npm install
        npm run build --if-present
    
    # Login to Azure with OIDC
    - name: Azure Login
      uses: azure/login@v1.6.0
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    # Deploy to Azure Web App
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
        runtime-version: NODE|${{ env.RUNTIME_NODE_VERSION }}
        startup-command: 'bash startup.sh'
        package: '.'  # Deploy the entire current directory
    
    - name: Verify deployment
      run: |
        echo "Backend deployment to Azure Web App completed successfully!"
        echo "API URL: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
