name: Deploy Backend to Azure Web App

on:
  push:
    branches: [dev]
    paths:
      - '**'
      - '!frontend/**'  # Exclude frontend changes from triggering backend deployment
  workflow_dispatch:

env:
  NODE_VERSION: '22.x'
  AZURE_WEBAPP_NAME: 'navi-backend'
  NODE_ENV: 'production'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
    
    - name: Install dependencies
      run: npm ci
      env:
        NODE_ENV: development
    
    - name: Build (if needed)
      run: npm run build --if-present
    
    - name: Install production dependencies
      run: npm ci --only=production
      env:
        NODE_ENV: production
    
    # Create .env file for production
    - name: Create production .env
      run: |
        cat > .env << 'EOL'
        NODE_ENV=production
        PORT=8080
        MONGODB_URI=${{ secrets.MONGODB_URI }}
        JWT_SECRET=${{ secrets.JWT_SECRET }}
        JWT_EXPIRE=30d
        JWT_COOKIE_EXPIRE=30
        # Add other required environment variables here
        EOL
    
    # Login to Azure
    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Create Azure Web App if it doesn't exist
    - name: 'Create Azure Web App'
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          if ! az webapp show --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group nav_hosting --query "name" -o tsv; then
            echo "Creating Azure Web App..."
            az webapp create \
              --name ${{ env.AZURE_WEBAPP_NAME }} \
              --resource-group nav_hosting \
              --runtime "NODE|20-lts" \
              --plan "navi-plan" \
              --deployment-local-git
          else
            echo "Web App already exists, skipping creation."
          fi

    # Deploy to Azure Web App
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'Production'
        package: .
    
    - name: Verify deployment
      run: |
        echo "Backend deployment to Azure Web App completed successfully!"
        echo "API URL: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
