name: Deploy Backend to Azure Web App

on:
  push:
    branches: [dev]
    paths:
      - '**'
      - '!frontend/**'
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'navi-backend'
  AZURE_RESOURCE_GROUP: 'nav_hosting'
  NODE_VERSION: '22.x'
  RUNTIME_NODE_VERSION: '22-lts'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci
        npm run build --if-present
    
    - name: Create production .env
      run: |
        echo "NODE_ENV=production" > .env
        echo "PORT=3000" >> .env
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
        echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
        echo "JWT_EXPIRE=30d" >> .env
        echo "JWT_COOKIE_EXPIRE=30" >> .env
        
        # Make startup script executable
        chmod +x startup-command.sh
    
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Configure Azure Web App
      uses: azure/CLI@v1
      with:
        inlineScript: |
          # Set Node.js runtime version
          az webapp config set \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --linux-fx-version "NODE|${{ env.RUNTIME_NODE_VERSION }}"
          
          # Configure app settings and startup command
          az webapp config appsettings set \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --settings \
              NODE_ENV=production \
              PORT=3000 \
              WEBSITE_NODE_DEFAULT_VERSION=${{ env.RUNTIME_NODE_VERSION }} \
              WEBSITE_RUN_FROM_PACKAGE=1 \
              SCM_DO_BUILD_DURING_DEPLOYMENT=false
              
          # Set the startup command
          az webapp config set \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
            --startup-file "startup-command.sh"
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: .
    
    - name: Verify deployment
      run: |
        echo "Backend deployment to Azure Web App completed successfully!"
        echo "API URL: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
