name: Deploy Frontend to Azure Web App

on:
  push:
    branches: [dev]
  workflow_dispatch:

env:
  NODE_VERSION: '22.x'
  AZURE_WEBAPP_NAME: 'naviWeb'
  NODE_ENV: 'production'
  APP_LOCATION: 'frontend'  # Define APP_LOCATION here

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
    
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci --legacy-peer-deps
    
    - name: Build frontend
      working-directory: ./frontend
      env:
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL || 'https://naviweb-a5gwdnhwcjazabdt.centralindia-01.azurewebsites.net/api' }}
      run: |
        npm run build
    
    # Create a simple server to serve the frontend
    # Move build files to the correct location
    - name: Prepare deployment files
      run: |
        # Create a temporary directory for the deployment
        mkdir -p deploy
        
        # Create server.js in the root of the deployment package
        cat > deploy/server.js << 'EOL'
        const express = require('express');
        const path = require('path');
        const app = express();
        
        // Serve static files from the React app
        app.use(express.static(path.join(__dirname, 'build')));
        
        // Handle React routing, return all requests to React app
        app.get('*', (req, res) => {
          res.sendFile(path.join(__dirname, 'build', 'index.html'));
        });
        
        const PORT = process.env.PORT || 3000;
        app.listen(PORT, () => {
          console.log(`Server is running on port ${PORT}`);
        });
        EOL
        
        # Copy the built files to the deployment directory
        cp -r frontend/build deploy/
        
        # Create package.json in the deployment directory
        cat > deploy/package.json << 'EOL'
        {
          "name": "navi",
          "version": "1.0.0",
          "description": "Navi Web Application",
          "main": "server.js",
          "scripts": {
            "start": "node server.js"
          },
          "dependencies": {
            "express": "^4.18.2"
          }
        }
        EOL
    
    # Install production dependencies and deploy
    - name: Install production dependencies and deploy
      working-directory: ./deploy
      run: |
        npm install --production
        
    # Deploy to Azure Web App
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'Production'
        package: ./deploy
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F974CCD36B0C4C6A9B7D0BC349107EBB }}
    
    - name: Verify deployment
      run: |
        echo "Frontend deployment to Azure Web App completed successfully!"
        echo "Application URL: https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
