name: Build and deploy Node.js app to Azure Web App - naviWeb

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js version
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: 'frontend/package-lock.json'
    
    - name: Install root dependencies
      run: |
        npm install -g serve
        
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: |
        npm ci --legacy-peer-deps
        
    - name: Build frontend
      working-directory: ./frontend
      env:
        NODE_ENV: production
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL || 'https://naviweb-a5gwdnhwcjazabdt.centralindia-01.azurewebsites.net/api' }}
      run: |
        npm run build
        
    - name: Create server.js
      run: |
        echo 'const express = require("express");' > server.js
        echo 'const path = require("path");' >> server.js
        echo 'const app = express();' >> server.js
        echo 'app.use(express.static(path.join(__dirname, "build")));' >> server.js
        echo 'app.get("*", (req, res) => {' >> server.js
        echo '  res.sendFile(path.join(__dirname, "build", "index.html"));' >> server.js
        echo '});' >> server.js
        echo 'const port = process.env.PORT || 3000;' >> server.js
        echo 'app.listen(port, () => console.log(`Server running on port ${port}`));' >> server.js
    
    - name: Create package.json in root
      run: |
        echo '{"name":"navi","version":"1.0.0","description":"","main":"server.js","scripts":{"start":"node server.js"},"dependencies":{"express":"^4.18.2"}}' > package.json
    
    - name: Copy build files to root
      run: |
        cp -r frontend/build .
        
    - name: Install production dependencies in root
      run: |
        npm install --production
        
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'naviWeb'
        slot-name: 'Production'
        package: .
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F974CCD36B0C4C6A9B7D0BC349107EBB }}
        
    - name: Verify deployment
      run: |
        echo "Deployment to Azure Web App completed successfully!"