name: Deploy Frontend to Azure Static Web App

on:
  push:
    branches: [dev]
  workflow_dispatch:

env:
  NODE_VERSION: '22.x'
  AZURE_WEBAPP_NAME: 'naviWeb'
  NODE_ENV: 'production'
  APP_LOCATION: 'frontend'    # Location of your React app
  OUTPUT_LOCATION: 'build'    # Location of the build output

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: '${{ env.APP_LOCATION }}/package-lock.json'
    
    - name: Install frontend dependencies
      working-directory: ${{ env.APP_LOCATION }}
      run: npm ci --legacy-peer-deps
    
    - name: Build frontend
      working-directory: ${{ env.APP_LOCATION }}
      env:
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL || 'https://naviweb-a5gwdnhwcjazabdt.centralindia-01.azurewebsites.net/api' }}
      run: |
        npm run build
    
    - name: Deploy to Azure Static Web App
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: 'upload'
        app_location: ${{ env.APP_LOCATION }}
        output_location: ${{ env.OUTPUT_LOCATION }}
        skip_app_build: true
    
    - name: Verify deployment
      run: |
        echo "Frontend deployment to Azure Static Web App completed successfully!"
        echo "Application URL: https://${{ env.AZURE_WEBAPP_NAME }}.azurestaticapps.net"
